# Generated by Django 6.0.3 on 2026-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_users_temp_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
